import { IdentityUserContext } from "./AICFOGovernanceTypes";
import { getRoleGovernancePolicy } from "./AICFORoleMatrix";

export class AICFOResponseFilter {
  /**
   * Scans and sanitizes the final text generated by AI or heuristic fallback.
   */
  public static sanitizeResponseText(
    responseText: string,
    userContext: IdentityUserContext
  ): string {
    if (!responseText) return "";
    const policy = getRoleGovernancePolicy(userContext.role);

    let sanitized = responseText;

    // If role cannot view individual salaries, redact any pattern matching "salaire de [Name]: [Amount]" or "$X,XXX" with name
    if (!policy.individualSalaryVisible) {
      // Regex pattern for salary leaks with specific numbers associated to individual employee names
      sanitized = sanitized.replace(
        /(salaire de|paye de|remuneration de|gagne)\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+)?)\s*(?:est de|:)?\s*([0-9\s,.$€HTGUSD]+)/gi,
        "$1 $2 est [MASQUÉ SECRETS RH]"
      );
    }

    // If role cannot view company profit or net margin, redact raw total profit numbers for non-owners
    if (!policy.companyProfitVisible) {
      sanitized = sanitized.replace(
        /(profit net global|benefice net du groupe|marge nette globale)\s*(?:est de|:)?\s*([0-9\s,.$€HTGUSD]+)/gi,
        "$1: [CONFIDENTIEL DIRECTION]"
      );
    }

    return sanitized;
  }
}
