import React, { useState, useMemo } from "react";
import { 
  ShieldCheck, 
  Smartphone, 
  Monitor, 
  CheckCircle2, 
  XCircle, 
  Layers, 
  HelpCircle,
  Eye,
  KeyRound
} from "lucide-react";
import { ERP_MODULES, STANDARD_ROLE_METADATA, AVAILABLE_PERMISSIONS, getRoleKey, getRoleMetadata } from "./types";
import { NavigationBuilder } from "../../../../../services/auth/resolvers";

interface RoleAccessSimulatorProps {
  roles: string[];
  roleModuleMatrix: Record<string, Record<string, boolean>>;
  permissionMatrix: Record<string, string[]>;
}

export const RoleAccessSimulator: React.FC<RoleAccessSimulatorProps> = ({
  roles,
  roleModuleMatrix,
  permissionMatrix,
}) => {
  const initialRole = getRoleKey(roles[0]) || "EMPLOYEE";
  const [simulatedRole, setSimulatedRole] = useState<string>(initialRole);
  const [simulatedLang, setSimulatedLang] = useState<"fr" | "ht" | "en">("fr");
  const [testPermissionId, setTestPermissionId] = useState<string>("payroll.run");

  const normalizedSimulatedRole = getRoleKey(simulatedRole);
  const meta = getRoleMetadata(normalizedSimulatedRole);


  // Mock translation object for NavigationBuilder
  const mockTranslations = {
    navigation: {
      bi: "Analyse Décisionnelle",
      personnel: "Directoire du Personnel",
      attendance: "Badgeuse Biométrique",
      payroll: "Calculateur de Paie",
      ledger: "Grand Livre",
      forensic: "Pistes d'Audit",
      health: "Console Métriques",
      reliability: "Flux d'Événements",
      recovery: "Plan de Continuité",
      aicfo: "Intelligence CFO",
      employeeSpace: "Espace Salarié",
      settings: "Paramètres",
    },
    organization: { title: "Structure d'Entreprise" },
    planning: { title: "Plannings Opérationnels" },
    leave: { title: "Gestion des Congés" },
    documents: { title: "Gestion Documentaire" },
  };

  // Compute navigation tabs that would be generated by NavigationBuilder
  const visibleTabs = useMemo(() => {
    return NavigationBuilder.build(normalizedSimulatedRole, simulatedLang, mockTranslations);
  }, [normalizedSimulatedRole, simulatedLang, roleModuleMatrix]);

  const isModuleGranted = (moduleId: string): boolean => {
    if (normalizedSimulatedRole === "SUPER_ADMIN") return true;
    const modLower = moduleId.toLowerCase();
    if (modLower === "forensic") {
      return ["SUPER_ADMIN", "OWNER", "ADMIN"].includes(normalizedSimulatedRole);
    }
    if (["health", "system_health", "reliability", "resilience_dlq", "dlq", "recovery", "disaster_recovery"].includes(modLower)) {
      return false;
    }
    if (normalizedSimulatedRole === "OWNER") return true;
    const config = roleModuleMatrix[normalizedSimulatedRole];
    if (config && config[moduleId] !== undefined) {
      return Boolean(config[moduleId]);
    }
    const mod = ERP_MODULES.find(m => m.id === moduleId);
    return mod ? mod.defaultRoles.includes(normalizedSimulatedRole) : false;
  };

  const isPermissionGranted = (permId: string): boolean => {
    if (normalizedSimulatedRole === "SUPER_ADMIN" || normalizedSimulatedRole === "OWNER") return true;
    const perms = permissionMatrix[normalizedSimulatedRole] || [];
    return perms.includes(permId);
  };

  return (
    <div className="space-y-6" id="role-access-simulator-root">
      {/* Simulation Controls */}
      <div className="p-5 bg-slate-900/60 border border-slate-800 rounded-2xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center text-cyan-400">
            <Eye className="w-5 h-5" />
          </div>
          <div>
            <h4 className="text-sm font-bold text-slate-100">Simulateur d'Expérience & Audit d'Accès</h4>
            <p className="text-xs text-slate-400">
              Visualisez exactement ce qu'un utilisateur avec ce rôle percevra dans son espace de travail.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3 w-full md:w-auto">
          <div className="flex-1 md:flex-none">
            <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">
              Rôle à Simuler
            </label>
            <select
              value={normalizedSimulatedRole}
              onChange={(e) => setSimulatedRole(e.target.value)}
              className="w-full md:w-48 px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-xs text-slate-200 focus:outline-none focus:border-cyan-500 font-bold"
            >
              {roles.map(rawRole => {
                const r = getRoleKey(rawRole);
                const roleMeta = getRoleMetadata(r);
                return (
                  <option key={r} value={r}>
                    {roleMeta.label}
                  </option>
                );
              })}
            </select>
          </div>


          <div>
            <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">
              Langue
            </label>
            <select
              value={simulatedLang}
              onChange={(e) => setSimulatedLang(e.target.value as any)}
              className="px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-xs text-slate-200 focus:outline-none focus:border-cyan-500"
            >
              <option value="fr">Français</option>
              <option value="ht">Kreyòl</option>
              <option value="en">English</option>
            </select>
          </div>
        </div>
      </div>

      {/* Side-by-side Simulation Views */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Navigation Sidebar Preview */}
        <div className="lg:col-span-6 space-y-4">
          <div className="p-4 bg-slate-900/40 border border-slate-800 rounded-2xl">
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-2">
                <Monitor className="w-4 h-4 text-cyan-400" />
                <span className="text-xs font-bold text-slate-200">
                  Menu & Onglets Visibles ({visibleTabs.length})
                </span>
              </div>
              <span className={`px-2 py-0.5 rounded text-[10px] font-bold border uppercase tracking-wider ${meta.badgeColor}`}>
                {meta.label}
              </span>
            </div>

            <div className="space-y-1.5 max-h-[380px] overflow-y-auto pr-1 custom-scrollbar">
              {visibleTabs.map((tab, idx) => (
                <div
                  key={tab.id}
                  className="flex items-center justify-between p-2.5 rounded-xl bg-slate-950/70 border border-slate-800/80 hover:border-slate-700 transition-colors"
                >
                  <div className="flex items-center gap-3">
                    <span className="text-[10px] font-mono text-slate-400 w-4 text-center">
                      {idx + 1}
                    </span>
                    <span className="text-xs font-semibold text-slate-200">
                      {tab.label}
                    </span>
                  </div>
                  <span className="text-[9px] font-mono px-1.5 py-0.5 rounded bg-slate-900 text-cyan-400 border border-slate-800">
                    tab: {tab.id}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Real-Time Permission & Module Authorization Check */}
        <div className="lg:col-span-6 space-y-4">
          {/* Permission Quick Check */}
          <div className="p-4 bg-slate-900/40 border border-slate-800 rounded-2xl space-y-4">
            <div className="flex items-center gap-2">
              <KeyRound className="w-4 h-4 text-cyan-400" />
              <span className="text-xs font-bold text-slate-200">
                Testeur de Capacité / Action Métier
              </span>
            </div>

            <div className="flex gap-2">
              <select
                value={testPermissionId}
                onChange={(e) => setTestPermissionId(e.target.value)}
                className="flex-1 px-3 py-2 bg-slate-950 border border-slate-800 rounded-xl text-xs text-slate-200 focus:outline-none focus:border-cyan-500"
              >
                {AVAILABLE_PERMISSIONS.map(p => (
                  <option key={p.id} value={p.id}>
                    {p.label} ({p.id})
                  </option>
                ))}
              </select>
            </div>

            <div className={`p-4 rounded-xl border flex items-center justify-between ${
              isPermissionGranted(testPermissionId)
                ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-400"
                : "bg-rose-500/10 border-rose-500/30 text-rose-400"
            }`}>
              <div className="flex items-center gap-2.5">
                {isPermissionGranted(testPermissionId) ? (
                  <CheckCircle2 className="w-5 h-5 shrink-0" />
                ) : (
                  <XCircle className="w-5 h-5 shrink-0" />
                )}
                <div>
                  <p className="text-xs font-bold">
                    {isPermissionGranted(testPermissionId) ? "Autorisation Accordée" : "Accès Rejeté / Bloqué"}
                  </p>
                  <p className="text-[10px] text-slate-400 mt-0.5">
                    Le rôle <span className="font-semibold text-slate-200">{meta.label}</span> {isPermissionGranted(testPermissionId) ? "dispose" : "ne dispose PAS"} du droit d'exécution pour <span className="font-mono">{testPermissionId}</span>.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Modules Clearance Overview */}
          <div className="p-4 bg-slate-900/40 border border-slate-800 rounded-2xl">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <Layers className="w-4 h-4 text-cyan-400" />
                <span className="text-xs font-bold text-slate-200">
                  Statut des 14 Modules ERP
                </span>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-2 max-h-[190px] overflow-y-auto pr-1 custom-scrollbar">
              {ERP_MODULES.map(m => {
                const granted = isModuleGranted(m.id);

                return (
                  <div
                    key={m.id}
                    className={`px-2.5 py-1.5 rounded-lg border text-[11px] flex items-center justify-between ${
                      granted
                        ? "bg-emerald-500/5 border-emerald-500/20 text-slate-200"
                        : "bg-slate-950/40 border-slate-800 text-slate-400"
                    }`}
                  >
                    <span className="truncate">{m.name}</span>
                    {granted ? (
                      <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 shrink-0 ml-1" />
                    ) : (
                      <XCircle className="w-3.5 h-3.5 text-slate-400 shrink-0 ml-1" />
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
